name = "p2p-clinic-signaling"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# KV for share codes and peer announcements (auto-expire)
[[kv_namespaces]]
binding = "KV"
id = "dcc764ce7d5f42d3a5849a3ec3cc3a14"
preview_id = "6645c7715e5e402eb26bb70e321285c2"

# Durable Objects for WebSocket signaling (optional)
[[durable_objects.bindings]]
name = "ROOM"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
